spring.application.name=waste-management
server.port=8081


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=waste_db;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123456789

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true

# Gemini API Configuration
gemini.api.key=AIzaSyAg5lOvzLj_gc2XPTYn6zxZfnNSzJfLDIs

# JWT Configuration
project.waste.jwtSecret=d2FzdGUtbWFuYWdlbWVudC1zZWNyZXQta2V5LTIwMjYtMDQtMDMtdGVzdGluZw==
project.waste.jwtExpirationMs=86400000